### PR TITLE
pf.conf example

### PR DESCRIPTION
**Pull request by bigio**
Do not allow everything by default, just add smtp and a commented line with everything else.

### CODE REVIEW

**Comment by wesley974** [comment]
I was thinking about a full mail server config like the following, plus at the end a cron job :

```
# EXAMPLE - MAIL SERVER
# Packet Filter configuration
# With rmspams support

table <blacksmtp> persist file "/var/db/rmspams/blacksmtp"

set fingerprints "/dev/null"
set skip on lo
block all

pass out

block quick log on egress from <blacksmtp>

pass in inet proto tcp from any to any \
        port { smtp www pop3 imap auth https smtps submission pop3s imaps ssh }

pass in inet proto icmp all icmp-type echoreq

# Make expire the blacksmtp table using a cron job:
#
# You should add these entries in your crontab(5)
#
#  0 0 * * * /sbin/pfctl -t blacksmtp -T expire 86400
# 10 0 * * * /sbin/pfctl -t blacksmtp -T show > /var/db/rmspams/blacksmtp
```

**Comment by bigio** [comment]
On Sat, Apr 22, 2017 at 06:17:59AM -0700, Wesley wrote:
> I was thinking about a full mail server config like the following, plus at the end a cron job :
> 
a full mail server may be split in several servers and/or could not provide all listed services.
 Giovanni

**Comment by wesley974** [comment]
Ok, where can i put the cron job ?

```
# Make expire the blacksmtp table using a cron job:
#
# You should add these entries in your crontab(5)
#
#  0 0 * * * /sbin/pfctl -t blacksmtp -T expire 86400
# 10 0 * * * /sbin/pfctl -t blacksmtp -T show > /var/db/rmspams/blacksmtp
```

**Comment by bigio** [comment]
On Sat, Apr 22, 2017 at 06:43:48AM -0700, Wesley wrote:
> Ok, where can i put the cron job ?
> 
I think in a readme file should be fine.

**Pull request merged**
